config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'
  resources :items do
    get 'new_item', to: 'items#new'
    post 'items', to: 'items#create' 
    get 'show', to: 'items#show'
    get 'confirm'
    post 'purchase'
    post 'done'
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren',defaults: { format: 'json' }
    end
  end

  resources :signup , only: [:index] do
      get '/signup/index', to:'signup#index'
  end

  resources :mypages, only: [:index] do
    get '/mypages', to: 'mypages#index'
  end

  resources :profiles, only: [:index] do
    get '/profiles', to: 'profiles#index'
  end

  resources :cards, only: [:index] do
    get '/cards', to: 'cards#index'
  end

  resources :identity_informations, only: [:index] do
    get '/identity_informations', to: 'identity_informations#index'
  end

  resources :cards, only: [:index] do
    get '/cards', to: 'cards#index'
  end

  resources :logouts, only: [:index] do
    get '/logouts', to: 'logouts#index'
  end
end

app/models/address.rb
class Address < ApplicationRecord

    belongs_to :user, optional: true
    belongs_to :prefecture
    
    VALID_POSTAL_CODE = /\A\d{3}-\d{4}\z/i
    VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/

    validates :address_firstname, presence: true, length: { maximum: 35 }
    validates :address_lastname, presence: true, length: { maximum: 35 }
    validates :address_kana_lastname, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}
    validates :address_kana_firstname, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}
    validates :municipalities, :address ,presence: true
    validates :zipcode, presence: true, length: { maximum: 8 }, format: { with: VALID_POSTAL_CODE, message: 'のフォーマットが不適切です' }
    validates :prefecture_id,presence: true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord

end

app/models/condition.rb
class Condition < ApplicationRecord
    has_many :items
end

app/models/delivery_burden.rb
class DeliveryBurden < ApplicationRecord
    has_many :items
end

app/models/delivery_day.rb
class DeliveryDay < ApplicationRecord
  has_many :items
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :src, ImageUploader
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, length: { maximum: 40 }
    validates :description, presence: true, length: { maximum: 1000 }
    validates :price, presence: true
    validates :condition_id, presence: true
    validates :prefecture_id, presence: true
    validates :delivery_day_id, presence: true
    validates :delivery_burden_id, presence: true
    validates :parent_category_id, presence: true
    validates :child_category_id, presence: true
    validates :category_id, presence: true

    validates_associated :images
    validates :images, presence: true

    belongs_to :user
    has_many :images, foreign_key: :item_id, dependent: :destroy
    accepts_nested_attributes_for :images
    belongs_to :category
    belongs_to :condition
    belongs_to :delivery_burden
    belongs_to :delivery_day

    belongs_to :prefecture
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :items
  has_many :users
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
  validates :uid,
  presence: true,
  uniqueness: { message: "既に存在しています" }
  validates :provider,
    presence: true
  validates :user_id,
    presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_KATAKANA_REGEX = /\A[\p{katakana}\p{blank}ー－]+\z/
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d!@#\$%\^\&*\)\(+=._-]{7,128}\z/i

  validates :nickname, :birthday, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX, message: 'のフォーマットが不適切です'}
  validates :lastname, presence: true, length: { maximum: 35 }
  validates :firstname, presence: true, length: { maximum: 35 }
  validates :password, presence: true, length: { in: 7..128 }, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字両方を含むパスワードを設定してください'}
  validates :kana_firstname, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}
  validates :kana_lastname, presence: true, length: { maximum: 35 }, format: { with: VALID_KATAKANA_REGEX, message: 'はカタカナで入力して下さい'}

  has_one :address
  has_many :sns_credentials
  has_many :items
  has_many :cards
  has_one :condition
  has_one :delivery_burden
  has_one :delivery_day


  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def index
  end
  def logout
  end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/logouts_helper.rb
module LogoutsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mypages/_side-bar.html.haml
.side-bar
  .mypage-nav
    %ul.mypage-box
      = link_to "#" do
        %li
          マイページ
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          お知らせ
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          やることリスト
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          いいね！一覧
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          出品する
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          ニュース一覧
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          評価一覧
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          ガイド
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          お問い合わせ
          %i.fas.fa-chevron-right
    %h3.mypage-head
      メルペイ
    %ul.mypage-box
      = link_to "#" do
        %li
          残高・振込申請
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          ポイント
          %i.fas.fa-chevron-right
    %h3.mypage-head
      設定
    %ul.mypage-box
      = link_to profiles_path do
        %li
          プロフィール
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      = link_to cards_path do
        %li
          支払い方法
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          メール/パスワード
          %i.fas.fa-chevron-right
      = link_to identity_informations_path do
        %li
          本人情報
          %i.fas.fa-chevron-right
      = link_to "#" do
        %li
          電話番号の確認
          %i.fas.fa-chevron-right
      = link_to logouts_path do
        %li
          ログアウト
          %i.fas.fa-chevron-right

app/views/mypages/index.html.haml
= render partial: './items/header'

- breadcrumb :index
= render "layouts/breadcrumbs"

.main1
  = render partial: 'side-bar'

  .main-bar
    .main-bar__top-box
      = link_to "#" do
        = image_tag "/hito.png", class:"picture", height:"auto", width:"65"
        %p.user_name 山田 太郎
      %p.user_info 評価数 0 出品数 0
    .main-bar__center-box
      .container1
        %ul.menu1
          %li
            #about.menu_item1.active1 お知らせ
          %li
            #service.menu_item1 やることリスト
        %ul.contents1
          %li.content1.show1
            = image_tag "/logo_gray.svg", class:"picture", height:"120", width:"120"
            %p 現在、お知らせはありません
          %li.content1
            = image_tag "/logo_gray.svg", class:"picture", height:"120", width:"120"
            %p 現在、やることリストはありません
    .main-bar__bottom-box
      .top 
        購入した商品
      .container2
        %ul.menu2
          %li
            #about.menu_item2.active2 取引中
          %li
            #service.menu_item2 過去の取引
        %ul.contents2
          %li.content2.show2
            = image_tag "/logo_gray.svg", class:"picture", height:"120", width:"120"
            %p 取引中の商品がありません
          %li.content2
            = image_tag "/logo_gray.svg", class:"picture", height:"120", width:"120"
            %p 過去に取引した商品がありません
= render partial: './items/footer'