config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root 'items#index'
  resources :items do
    get 'new_item', to: 'items#new'
    post 'items', to: 'items#create' 
    get 'show', to: 'items#show'
    get 'confirm'
    post 'purchase'
    post 'done'
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren',defaults: { format: 'json' }
    end
  end

  resources :signup , only: [:index] do
      get '/signup/index', to:'signup#index'
  end

  resources :mypages, only: [:index] do
    get '/mypages', to: 'mypages#index'
  end

  resources :profiles, only: [:index] do
    get '/profiles', to: 'profiles#index'
  end

  resources :cards, only: [:index] do
    get '/cards', to: 'cards#index'
  end

  resources :identity_informations, only: [:index] do
    get '/identity_informations', to: 'identity_informations#index'
  end

  resources :cards, only: [:index] do
    get '/cards', to: 'cards#index'
  end

  resources :logouts, only: [:index] do
    get '/logouts', to: 'logouts#index'
  end
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, length: { maximum: 40 }
    validates :description, presence: true, length: { maximum: 1000 }
    validates :price, presence: true
    validates :condition_id, presence: true
    validates :prefecture_id, presence: true
    validates :delivery_day_id, presence: true
    validates :delivery_burden_id, presence: true
    validates :parent_category_id, presence: true
    validates :child_category_id, presence: true
    validates :category_id, presence: true

    validates_associated :images
    validates :images, presence: true

    belongs_to :user
    has_many :images, foreign_key: :item_id, dependent: :destroy
    accepts_nested_attributes_for :images
    belongs_to :category
    belongs_to :condition
    belongs_to :delivery_burden
    belongs_to :delivery_day

    belongs_to :prefecture
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only:[:destroy,:update,:edit]

  def index
    @items = Item.includes(:images).order('created_at DESC')
    @ladies = Item.where(parent_category_id:'1').order("created_at DESC").limit(10)
    @mens = Item.where(parent_category_id:'200').order("created_at DESC").limit(10)
    @elect = Item.where(parent_category_id:'898').order("created_at DESC").limit(10)

  end

  def confirm
    @item = Item.includes(:images).find(params[:item_id])
  end

  require 'payjp'
  def purchase
    Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    @item = Item.find(params[:item_id])
    Payjp::Charge.create(
      amount: @item.price, 
      card: params['payjp-token'], 
      currency: 'jpy'
    )
    redirect_to root_path
  end

  def  done
    @item_purchaser= Item.find(params[:item_id])
    if @item_purchaser.update( purchaser: current_user.id)
      @item_purchaser.destroy
    else
      item_confirm_path(@item_purchaser.id)
   end
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def get_category_children
    @category_children = Category.find_by(id: "#{params[:parent_id]}",ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find_by(id: "#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path
    end
  end

  def show
    @item = Item.includes(:images).find(params[:item_id])
    @items = Item.find(params[:item_id])
  end

  def edit
    @child_number = @item.child_category_id
    @child_category = Category.find(@child_number)
    @child = @child_category.ancestry
    @child_name = @child_category.name
    @grandchild = @item.category.ancestry
    @grandchild_name = @item.category.name
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      edit_item_path
    end
  end

  def destroy 
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :condition_id, :prefecture_id, :delivery_day_id, :delivery_burden_id, :parent_category_id, :child_category_id, :category_id, images_attributes: [:src]).merge(user_id: current_user.id)
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_brands.html.haml
.contents__popular-brands
  %h3.contents__popular-brands__title 人気のブランド
  %ul.contents__popular-brands__genres
    %li.contents__popular-brands__genres__genre1 シャネル
    %li.contents__popular-brands__genres__genre2 ルイヴィトン
    %li.contents__popular-brands__genres__genre3 シュプリーム
    %li.contents__popular-brands__genres__genre4 ナイキ

app/views/items/_contents-header.html.haml
.contents__header
  = image_tag "/baner1.jpg",class:'contents__header__img'
  .contents__header__box
    .contents__header__box__sentence
      %h3.contents__header__box__sentence__title スマホでかんたん
      %h3.contents__header__box__sentence__title フリマアプリ
      %p.contents__header__box__sentence__explain メルカリはスマホカメラからすぐに出品できる
      %p.contents__header__box__sentence__explain 購入時も安心な独自システムのアプリです
      .contents__header__box__sentence__app-links
        = link_to 'https://apps.apple.com/jp/app/id667861049?l=ja', class: 'contents__footer__box__sentence__app-links__apple' do
          = image_tag "/apple.svg",class:'contents__header__box__sentence__app-links__apple__img', width: "150", height: "50"
        = link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja', class: 'contents__footer__box__sentence__app-links__google' do
          = image_tag "/google.svg",class:'contents__header__box__sentence__app-links__link-google__img', width: "150", height: "50"
    = image_tag "/smartphone.png",class:'contents__header__box__smartphone',height:"390"

app/views/items/_create_address.html.haml
%header.single-header-five
  .header-min
    %h1
      = link_to root_path do
        = image_tag  "/fmarket_logo_red.svg"
    %nav
      %ol.clearfix
        %li.procedure_one
          会員情報
          %br/
          .progress-status
        %li.procedure_two
          電話番号認証
          %br/
          .progress-status
        %li.procedure_three
          お届け先住所
          %br/
          .progress-status
        %li.procedure_four
          支払い方法
          %br/
          .progress-status
        %li.procedure_five
          完了
          %br/
          .progress-status
%main.page-five
  %h2 会員登録完了
  %form
    .contents
      %p ありがとうございます。
      %p 会員登録が完了しました。
      %button{type: "submit"} メルカリをはじめる
  %link_to.banner
    %img{src: "//www-mercari-jp.akamaized.net/assets/img/signup/jp/banner-pc.jpg?2091621301", width: "100%"}
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %link_to{href: ""} プライバシーポリシー
      %li
        %link_to{href: ""} メルカリ利用規約
      %li
        %link_to{href: ""} 特定商取引に関する表記
  %link_to{href: "https://www.mercari.com/jp/"}
    %img{alt: "Fmarket", src: "/logo_gray.svg", height: "80", width: "65", class:"all__footer__picture"}
  %p
    %small © Fmarket, Inc.

app/views/items/_detail.html.haml
.product
  .product__item
    %h1.product__item__name バッグ
    .product__item__main
      .product__item__main__photo
        = image_tag "/319531408.jpg", style: "opacity: 1;"
        .product__item__main__photo__bottom
          = image_tag "/h-i289.jpg"
          = image_tag "/vuitton2.jpg"
          = image_tag "/vuitton3.jpeg"

      .product__item__main__detail
        .product__item__main__detail__tbody
          .product__item__main__detail__tbody__tr
            .product__item__main__detail__tbody__tr__th 出品者
            .product__item__main__detail__tbody__tr__td
              .product__item__main__detail__tbody__tr__td__name 太郎
              .product__item__main__detail__tbody__tr__td__icon
                .product__item__main__detail__tbody__tr__td__icon__rating
                  %i.product__item__main__detail__tbody__tr__td__icon__rating.fas.fa-laugh
                  %span 36
                .product__item__main__detail__tbody__tr__td__icon__rating
                  %i.product__item__main__detail__tbody__tr__td__icon__rating.fas.fa-meh
                  %span 0
                .product__item__main__detail__tbody__tr__td__icon__rating
                  %i.product__item__main__detail__tbody__tr__td__icon__rating.fas.fa-frown
                  %span 0


              
          .product__item__main__detail__tbody__tr-2
            .product__item__main__detail__tbody__tr-2__th カテゴリー
            .product__item__main__detail__tbody__tr-2__td レディース
          .product__item__main__detail__tbody__tr-3
            .product__item__main__detail__tbody__tr-3__th ブランド
            .product__item__main__detail__tbody__tr-3__td ヴィトン
          .product__item__main__detail__tbody__tr-4
            .product__item__main__detail__tbody__tr-4__th 商品の状態
            .product__item__main__detail__tbody__tr-4__td 目立った傷や汚れなし
          .product__item__main__detail__tbody__tr-5
            .product__item__main__detail__tbody__tr-5__th 配送料の負担
            .product__item__main__detail__tbody__tr-5__td 送料込み(出品者負担)
          .product__item__main__detail__tbody__tr-6
            .product__item__main__detail__tbody__tr-6__th 配送の方法
            .product__item__main__detail__tbody__tr-6__td らくらくメルカリ便
          .product__item__main__detail__tbody__tr-7
            .product__item__main__detail__tbody__tr-7__th 配送元地域
            .product__item__main__detail__tbody__tr-7__td 福岡県
          .product__item__main__detail__tbody__tr-8
            .product__item__main__detail__tbody__tr-8__th 発送日の目安
            .product__item__main__detail__tbody__tr-8__td 4日~7日で発送

    .product__item__price-box
      %span.product__item__price-box__price ¥1,200
      %span.product__item__price-box__tax (税込)
      %span.product__item__price-box__shipping-fee 送料込み
    = link_to "#" do
      .product__item__buy-btn
        購入画面に進む

    .product__item__description
      %p.product__item__description__inner
        2000円→1200円にお値下げいたします。
        %br
        %br
        定番のバッグで、大きさもしっかりあり、マザーズバッグやビジネスバッグになるかと思います。
        %br
        %br
        革特有のシワ感が少しありますが、リペアクリーニング済みのため目立った傷スレ汚れはないかと思います。作りがしっかりしてますので、まだまだデイリーに使えるかと思います。
        %br
        %br
        used品のためご理解頂ける方にお譲り致します。

    .product__item__text-box
      .product__item__text-box__left
        %button.product__item__text-box__left__like{type: "button"}
          %i.product__item__text-box__left__like.far.fa-heart
            %span いいね!
            %span 0
        .product__item__text-box__left__report
          %i.product__item__text-box__left__report.far.fa-flag
            %span 不適切な商品の報告
      .product__item__text-box__right
        %i.product__item__text-box__right.fas.fa-lock
        %span あんしん・あんぜんへの取り組み



  .product__detail-message
    .product__detail-message__box
      .product__detail-message__box__content
        %form.product__detail-message__box__content__message-form{action: "https://www.mercari.com/jp/comment/add/", method: "POST"}
          %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %textarea.product__detail-message__box__content__message-form__textarea{type: "text"}
          %button.product__detail-message__box__content__message-form__btn-gray{type: "submit"}
            %span コメントする 

  .product__nav-item
    .product__nav-item__box
      .product__nav-item__box__link
        ブルゾン
        .product__nav-item__box__link.fas.fa-angle-left
  
      .product__nav-item__box__link-2
        ワンピース
        .product__nav-item__box__link-2.fas.fa-angle-right

  .product__media
    .product__media__box
      %i.product__media__box__.fab.fa-facebook-square
      %i.product__media__box__.fab.fa-twitter-square
      %i.product__media__box__.fab.fa-pinterest-square

  .product__image
    .product__image__box
      %h2.product__image__box__head
        太郎さんのその他の出品
      .product__image__box__content
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/16088508301_main.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name ダウンジャケット
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥5,000
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/buruzon.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name ブルゾン
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥4,000
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/kardigan.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name カーディガン
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥3,000
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/gpants.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name gパン
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥3,500
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/torainer.jpeg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name トレーナー
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥5,500
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/tshats.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name tシャツ
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥2,000

    .product__image__box
      %h2.product__image__box__head ヴィトンのバッグその他の商品
      .product__image__box__content
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/vuiton.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name ヴィトン バッグ
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥5,000
        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/vuitton.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name vuitton
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥６,000

        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/louis.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name louis vuitton
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥7,000

        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/vuitton hand.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name louis vuitton ハンドバッグ
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥8,000

        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/vuitton1.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name louis vuitton ハンドバッグ 限定
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥8,500

        = link_to "#" do
          .product__image__box__content__box
            %figure.product__image__box__content__box__photo
              = image_tag "/vuitton pop.jpg",width:"220px",height:"220px"
            .product__image__box__content__box__body
              %h3.product__image__box__content__box__body__name louis vuitton ハンドバッグ pop
              .product__image__box__content__box__body__num
                .product__image__box__content__box__body__num__price ¥9,500

app/views/items/_electronics.html.haml
.contents__items
  .contents__items__main-box
    .contents__items__main-box__items-header 
      %h3.contents__items__main-box__items-header__title 家電・スマホ・カメラ新着アイテム
      = link_to 'もっと見る >', '#', class: 'contents__items__main-box__items-header__button' 
    %ul.contents__items__main-box__items
      - @elect.each do |elect|
        %li.contents__items__main-box__items__list
          = link_to item_show_path(elect.id), class: 'contents__items__main-box__items__list__link' do
            .contents__items__main-box__items__list__link__box
              .contents__items__main-box__items__list__link__box__img-box
                - elect.images.each do |image|
                  = image_tag image.src.to_s
                .contents__items__main-box__items__list__link__box__img-box__price-box
                  ¥
                  %span= elect.price
                .contents__items__main-box__items__list__link__box__desc-box
                  %span= elect.name

app/views/items/_footer.html.haml
.footer
  .footer__top
    .footer__top__box
      .footer__top__box__details
        %h2.footer__top__box__details__title
          メルカリについて
        %ul.footer__top__box__details__list
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              会社概要（運営会社）
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              採用情報
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              プレスリリース
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              公式ブログ
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              メルカリロゴ利用ガイドライン
        .iconbox  
          .twitter
            = link_to "https://twitter.com/mercari_jp" do
              = icon('fab', 'twitter', class: "icon")  
          .facebook  
            = link_to "https://www.facebook.com/mercarijp" do
              = icon('fab', 'facebook-square', class: "icon")
      .footer__top__box__help
        %h2.footer__top__box__help__title
          ヘルプ＆ガイド
        %ul.footer__top__box__help__list
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              メルカリガイド
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              らくらくメルカリ便
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              ゆうゆうメルカリ便
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              大型メルカリ便
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              車体取引ガイド
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              メルカリあんしん・あんぜん宣言！
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              偽ブランド品撲滅への取り組み
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              メルカリボックス
    .footer__top__privacy
      %h2.footer__top__privacy__title
        プライバシーと利用規約
      .footer__top__privacy__box
        %ul.footer__top__privacy__box__list
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              プライバシーポリシー
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              メルカリ利用規約
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              あんしんスマホサポート制度に関する利用特約
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              コンプライアンスポリシー
        %ul.footer__top__privacy__box__lists
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              個人データの安全管理に係る基本方針
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              特定商取引に関する表記
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              資金決済法に基づく表示
          %li
            = link_to "#", class: 'footer__top__box__details__list__info' do
              法令順守と犯罪抑止のために
    .footer__top__country
      %h2.footer__top__country__title
        国
      %ul.footer__top__country__list
        %li
          = link_to "#", class: 'footer__top__box__details__list__info' do
            日本
        %li
          = link_to "#", class: 'footer__top__box__details__list__info' do
            United States
  .footer__bottom
    = link_to "#", class: 'bb' do
      = image_tag "/logo_white.svg",width:"40",height:"40px"
      Fmarket
    .footer__bottom__center
      © Fmarket,inc.

app/views/items/_ladies.html.haml
.contents__items
  .contents__items__main-box
    .contents__items__main-box__items-header
      %h3.contents__items__main-box__items-header__title レディース新着アイテム
      = link_to 'もっと見る >', '#', class: 'contents__items__main-box__items-header__button' 
    %ul.contents__items__main-box__items
      - @ladies.each do |ladies|
        %li.contents__items__main-box__items__list
          = link_to item_show_path(ladies.id), class: 'contents__items__main-box__items__list__link' do
            .contents__items__main-box__items__list__link__box
              .contents__items__main-box__items__list__link__box__img-box
                - ladies.images.each do |image|
                  = image_tag image.src.to_s
                .contents__items__main-box__items__list__link__box__img-box__price-box
                  ¥
                  %span= ladies.price
                .contents__items__main-box__items__list__link__box__desc-box
                  %span= ladies.name

app/views/items/_mens.html.haml
.contents__items
  .contents__items__main-box
    .contents__items__main-box__items-header 
      %h3.contents__items__main-box__items-header__title メンズ新着アイテム
      = link_to 'もっと見る >', '#', class: 'contents__items__main-box__items-header__button'
    %ul.contents__items__main-box__items
      - @mens.each do |mens|
        %li.contents__items__main-box__items__list
          = link_to item_show_path(mens.id), class: 'contents__items__main-box__items__list__link' do
            .contents__items__main-box__items__list__link__box
              .contents__items__main-box__items__list__link__box__img-box
                - mens.images.each do |image|
                  = image_tag image.src.to_s
                .contents__items__main-box__items__list__link__box__img-box__price-box
                  ¥
                  %span= mens.price
                .contents__items__main-box__items__list__link__box__desc-box
                  %span= mens.name

app/views/items/_products-exhibition.html.haml
.all
    .all__header
        = link_to '/' do
            = image_tag  "/fmarket_logo_red.svg", class:"header-picture"
    = form_with(model:@item, local: true) do |f|     
        .all__main
            .all__main__contents


                .all__main__contents__top 商品の情報を入力

                .all__main__contents__images
                    .all__main__contents__images__head
                        出品画像
                        %span 必須
                    %p.column 最大10枚までアップロードできます
                    %label
                        .all__main__contents__images__square
                            ドラッグアンドドロップ
                            %br/
                            またはクリックしてファイルをアップロード
                            = f.file_field :image
                        
                    

                .all__main__contents__products
                    .all__main__contents__products__name
                        商品名
                        %span 必須
                        = f.text_field :name, placeholder: "商品名  (必須40文字まで)", class:"name-column"
                    
                    -# %input.name-column{type:"text", placeholder:"商品名  (必須40文字まで)"}
                    .all__main__contents__products__description
                        商品の説明
                        %span 必須
                        = f.text_area :description, placeholder:"商品の説明 (必須1,000文字いない)  (色、素材、重さ、定価、注意点など)    例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです。", class:"description-column"

                    -# %textarea.description-column{placeholder:"商品の説明 (必須1,000文字いない)  (色、素材、重さ、定価、注意点など) 例)        2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。合わせやすいのでオススメです。"}
                    
                .all__main__contents__details
                    .all__main__contents__details__left-box
                        %p 商品の詳細
                    .all__main__contents__details__right-box
                        .all__main__contents__details__right-box__category
                            カテゴリー
                            %span 必須
                        = f.collection_select :category_id, Category.all, :id, :name, prompt:"---"
                        
                        .all__main__contents__details__right-box__condition
                            商品の状態
                            %span 必須
                        = f.collection_select :condition_id, Condition.all, :id, :value, prompt:"---"

                .all__main__contents__delivery
                    .all__main__contents__delivery__left-box
                        %p 配送について
                        = link_to '' "?"
                    .all__main__contents__delivery__right-box
                        .all__main__contents__delivery__right-box__burden
                            配送料の負担
                            %span 必須
                            = f.collection_select :delivery_burden_id, DeliveryBurden.all, :id, :value, prompt:"---"
                        
                        .all__main__contents__delivery__right-box__prefectures
                            発送元の地域
                            %span 必須
                            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt:"---"

                        .all__main__contents__delivery__right-box__dates
                            発送までの日数
                            %span 必須
                            = f.collection_select :delivery_days_id, DeliveryDays.all, :id, :value, prompt:"---"

                .all__main__contents__prices
                    .all__main__contents__prices__left-box
                        %p 販売価格(300~9,999,999)
                        = link_to '' "?"
                    .all__main__contents__prices__right-box
                        .all__main__contents__prices__right-box__top
                            .all__main__contents__prices__right-box__top__left
                                価格
                                %span 必須
                            .all__main__contents__prices__right-box__top__right
                                ¥
                                = f.number_field :price, placeholder:"                     例)300", class:"value"
                                -# %input.price{type:"text", placeholder:"                     例)300"}
                        .all__main__contents__prices__right-box__center
                            .all__main__contents__prices__right-box__center__left
                                販売手数料(10%)
                            .all__main__contents__prices__right-box__center__right
                                %p -
                        .all__main__contents__prices__right-box__bottom
                            .all__main__contents__prices__right-box__bottom__left
                                販売利益
                            .all__main__contents__prices__right-box__bottom__right
                                %p -


                .all__main__contents__bottom-box
                    .all__main__contents__bottom-box__caution
                        %p
                            = link_to '' "禁止されている出品"
                            、
                            = link_to '' "行為"
                            を必ずご確認ください。
                        %p
                            またブランド品でシリアルナンバー等がある場合はご記載ください。
                            = link_to '' "偽ブランドの販売"
                            は犯罪であり処罰される可能性があります。
                        %p
                            また、出品をもちまして
                            = link_to '' "加盟店規約"
                            に同意したことになります。
                            = f.submit :"出品する", class:"exhibition"
                            -# %button.exhibition{type:"submit", value:"/items"}
                            -#     出品する

                        %button.return{type:"submit", value:"#"}
                            もどる


    .all__footer
        .all__footer__texts
            = link_to '' "プライバシーポリシー"
            = link_to '' "メルカリ利用規約"
            = link_to '' "特定商取引に関する表記"
        = image_tag "/logo_gray.svg", class:"all__footer__picture"

app/views/items/index.html.haml
= render partial: 'header'
.contents
  = render partial: 'contents-header'
  = render partial: 'new-item'
  = render partial: 'ladies'
  = render partial: 'mens'
  = render partial: 'electronics'
  = render partial: 'contents-footer'
  = render partial: 'sell'
= render partial: 'footer'